### ISSUE TITLE
Multiple migrators running the same set of jobs will duplicate work

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#84]
This is because a migrator will greedy fetch all jobs and keep them in memory. So even after a job is updated by another migrator, other instance would never get that information as it has already essentially been cached.

**Comment by jewzaam** [comment]
To solve this we need state for job executions: https://github.com/lightblue-platform/lightblue-migrator/issues/82
And once that is there it could be used to check that some other thread is not processing the job.  For example, if the thread were append a jobExecution object and verify it is the only in progress executor it would be OK to proceed.  And if there are more than one jobExecutor that are in progress it should only proceed if it is the first executor in the list.  Otherwise the thread must terminate without doing work.
