### ISSUE TITLE
Need better status on job executions

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-migrator#97]
Right now there's just a boolean flag indicating if the job execution is complete (jobExecutions.*.isComplete).  If the source for the job has no documents then there is no way to distinguish this job execution from an execution that was terminated for some other reason (running too long, process died, aborted because of duplicate processing).

I propose removing isComplete and replacing it with a string field 'statusCode' that is backed by an enum.  Values of the enum would be something like:
* running - currently being processed
* abort_duplicate - execution aborted because it was a duplicate
* abort_timeout - execution aborted because of timeout (running too long)
* complete_failed - execution completed but failed
* complete_partial - execution completed but only partially
* complete_success - execution completed successfully

**Comment by luan-cestari** [comment]
Some thought I had: we have com.redhat.lightblue.OperationStatus enum with the values  COMPLETE, PARTIAL, ASYNC, ERROR . I think most of them was mapped by the Naveen's suggestion, just think that ASYNC should have its own value represented there as well . I will re-write the list just to make my suggestion and I will try to complement the comments as I think this can also be useful and part of in our documentation.

* running - currently being processed for synchronous request
* running_async - currently being asynchronously processed
* abort_duplicate - execution aborted because it was a duplicate
* abort_timeout - execution aborted because of timeout (running too long) (can't be due some lightblue constraint or external constraints like MongoDB server)
* abort_auth - execution aborted due authentication/authorization issues
* abort_unknown- execution aborted due another problem not listed here and lightblue was able to identify (maybe an external issue not mapped)
* complete_failed - execution completed but failed (for know exceptions like bad request, entity doesn exist, etc)
* complete_partial - execution completed but only partially (at least one part of the request was successfully processed and at least one part of the request failed )
* complete_success - execution completed successfully

**Comment by jewzaam** [comment]
+1

**Comment by luan-cestari** [comment]
As nobody gave another suggestion, I will implemented this for now

**Comment by luan-cestari** [comment]
@jewzaam I create the PR https://github.com/lightblue-platform/lightblue-migrator/pull/120 which is in_progress as we can evaluate the states of the new enum. if you or someone else want to drop a suggestion or anything on the PR or here so we can enhance it. The PR is in_progress as I just converted the previous flag to this new enum, but need further work such as updating the status according to the job state.

**Comment by dcrissman** [comment]
I believe jobExecutions.*.completedFlag is the actual field name.
